
package forumdb.EntitiesFrames.Post;

import EntitiesClasses.Post;
import EntitiesClasses.Section;
import EntitiesClasses.Customer;
import Help.JTextFieldLimit;
import forumdb.EntitiesFrames.Customer.NewCustomer;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

public class NewPost extends javax.swing.JDialog {

    Connection c;
    Post editItem;
    List<Section> list;
    List<Customer> list1;

    public NewPost(java.awt.Frame parent, boolean modal, Connection c) {
        super(parent, modal);
        initComponents();
        ((AbstractDocument) text.getDocument()).setDocumentFilter(new JTextFieldLimit(1024));
        this.c = c;
        list = new ArrayList<>();
        list1 = new ArrayList<>();

        try {
            Statement statement = c.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM \"Section\"");
            while (rs.next()) {
                Section item = new Section(rs.getInt("ID_sect"), rs.getString("Name_sect"));
                list.add(item);
            }
            section.setModel(new DefaultComboBoxModel(list.toArray()));

            rs = statement.executeQuery("SELECT * FROM \"Customer\"");
            while (rs.next()) {
                Customer item = new Customer(rs.getInt("ID_cust"), rs.getString("Login"), rs.getString("Password"),
                        rs.getInt("ID_role"), rs.getString("Family"),
                        rs.getString("Name"), rs.getString("Patronymic"), rs.getString("Email"));
                list1.add(item);
            }
            user.setModel(new DefaultComboBoxModel(list1.toArray()));

        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public NewPost(java.awt.Frame parent, boolean modal, Connection c, Post u) {
        super(parent, modal);
        initComponents();
        ((AbstractDocument) text.getDocument()).setDocumentFilter(new JTextFieldLimit(1024));
        this.c = c;
        editItem = u;
        list = new ArrayList<>();
        list1 = new ArrayList<>();

        try {
            Statement statement = c.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM \"Section\"");
            while (rs.next()) {
                Section item = new Section(rs.getInt("ID_sect"), rs.getString("Name_sect"));
                list.add(item);
            }
            section.setModel(new DefaultComboBoxModel(list.toArray()));

            rs = statement.executeQuery("SELECT * FROM \"Customer\"");
            while (rs.next()) {
                Customer item = new Customer(rs.getInt("ID_cust"), rs.getString("Login"), rs.getString("Password"),
                        rs.getInt("ID_role"), rs.getString("Family"),
                        rs.getString("Name"), rs.getString("Patronymic"), rs.getString("Email"));
                list1.add(item);
            }
            user.setModel(new DefaultComboBoxModel(list1.toArray()));

        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillFields();
    }

    private void fillFields() {
        text.setText(editItem.getText());
        for (Section s : list) {
            if (s.getID_sect() == editItem.getID_sect()) {
                section.setSelectedItem((s));
            }
        }
        for (Customer s : list1) {
            if (s.getID_cust() == editItem.getID_cust()) {
                user.setSelectedItem((s));
            }
        }
    }

    public boolean check() {
        if ("".equals(text.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Name cannot be empty");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        section = new javax.swing.JComboBox<>();
        user = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New question");

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionActionPerformed(evt);
            }
        });

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Text");

        jLabel3.setText("Section");

        jLabel4.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(section, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!check()) {
            return;
        }
        try {
            // TODO add your handling code here:
            Statement statement = c.createStatement();
            if (editItem == null) {
                statement.executeUpdate("insert into \"Post\" (\"ID_cust\", \"ID_sect\", \"Text\")"
                        + " values ('" + ((Customer) user.getSelectedItem()).getID_cust() + "','" + ((Section) section.getSelectedItem()).getID_sect() + "','" + text.getText() + "');");
            } else {
                statement.executeUpdate("update \"Post\" set \"ID_cust\" = '" + ((Customer) user.getSelectedItem()).getID_cust() + "', \"ID_sect\" ='" + ((Section) section.getSelectedItem()).getID_sect() + "',\"Text\"='" + text.getText() + "' where \"ID_post\" = " + editItem.getID_post() + ";");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            return;
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                NewQuestion dialog = new NewQuestion(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> section;
    private javax.swing.JTextArea text;
    private javax.swing.JComboBox<String> user;
    // End of variables declaration//GEN-END:variables
}
